RTPROG = ../..

PROJECT = simtest
BOARD = rtboard
# DEVICE = 33EP256MU806
# ARCHI = dspic33ep
OUT_PWD = build

DRIVERS += uart

SRC += main.c

include $(RTPROG)/rtprog.mk

all : hex
	@echo OBJECTS: $(OBJECTS)
