RTPROG = ../..

BOARD = rtboard

DRIVERS += ax12 usbserial titi

-include $(RTPROG)/support/rtprog.mk


all :
	@echo $(DRIVERS)
	@echo $(DRIVER_FILES)
	@echo $(DEVICE) $(ARCHI) $(CC)
	@echo $(DRIVER_FILES) $(IDRIVERS)
	@echo $(BADDRIVERS)
	# $(CC) main.c
